### ISSUE TITLE
Conflict with fancybox

### ISSUE THREAD

**Issue by christian70** [benbarnett/jquery-animate-enhanced#127]
Hello. This jQuery plugin is very useful (I'm using it along with Superslides script) but on the other hand it causes a conflict with Fancybox because it changes the way that script calculates top and left positioning animation. Is there any way to prevent jQuery-Animate-Enhanced from working on divs where Fancybox is expected to be activated? I red the instructions coming with the plugin but I didn't fix it. Any help will be appreciated. Thanx.

**Comment by intsfanatic** [comment]
Tried your method Ipshal, when scrolling the page via mousewheel, the fancybox window still jumps back and forth between top left and center. Any other solution?
