### ISSUE TITLE
Bower install issue

### ISSUE THREAD

**Issue by roaringskyinc** [benbarnett/jquery-animate-enhanced#160]
Doing bower install results in:

ENOTFOUND Package benbarnett/jQuery-Animate-Enhanced=benbarnett/jQuery-Animate-Enhanced not found

You may need to update your bower.json with the recent build number and remove your repo name from the package name, so:
```
"name":"jQuery-Animate-Enhanced"
```

**Comment by antongorodezkiy** [comment]
+1

**Comment by benbarnett** [comment]
Fixed
